LayerConfig:
  1:
    name: Embedding
    params: {}
    state: src
    layer_limits:
      - embedding
    to:
      - 2
    from: []
    layer_nums: 1
  2:
    name: Decoderlayer1
    params: {}
    state: none
    layer_limits:
      - Qwen2DecoderLayer
    to: []
    from:
      - 1
    layer_nums: 1
