# 额外PYTHONPATH设置，需要预先配置环境变量$MSAPATH

export PYTHONPATH=$PTAPATH:$PTAPATH/MindSpeed:$PTAPATH/MindSpeed-MM:$PTAPATH/Megatron-LM

export HCCL_DETERMINISTIC=true 
export ASCEND_LAUNCH_BLOCKING=1 
export NCCL_DETERMINISTIC=1